name: Create Release on Test Pass

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (or your desired branch)

jobs:
  test-and-release:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Use your required Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      - name: Run pytest
        run: |
          pytest . --maxfail=1 --disable-warnings -q  # Run pytest in the current directory

      - name: Create release if tests pass
        if: success()  # Only run if the previous step (pytest) succeeded
        run: |
          # Generate a tag for the release based on commit SHA or version
          TAG=$(git rev-parse --short HEAD)  # Or use any versioning method you prefer

          # Create a GitHub release
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"tag_name": "v$TAG", "name": "Release v$TAG", "body": "Release after successful tests."}' \
            https://api.github.com/repos/${{ github.repository }}/releases
