name: Create Release on Test Pass

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (or your desired branch)

jobs:
  test-and-release:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # This will fetch the submodules as well

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Use your required Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      - name: Run pytest
        run: |
          pytest . --maxfail=1 --disable-warnings -q  # Run pytest in the current directory

      - name: Create release if tests pass
        if: success()  # Only run if the previous step (pytest) succeeded
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: $(git rev-parse --short HEAD)	#${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false


